### ISSUE TITLE
Readme Issue

### ISSUE THREAD

**Issue by Monoverde888** [MadMax1960/Femc-Reloaded-Project#170]
The "copyright" symbol in the readme that says ⓒAtlus ⓒSega is actually not a copyright symbol, it’s a CIRCLED LATIN SMALL LETTER C
 (U+24D2) whereas the actual copyright symbol is © COPYRIGHT SIGN (U+00A9) please fix or i will die

**Comment by MadMax1960** [comment]
Unfortunately this sounds really funny to leave now so I am conflicted

**Comment by TheBestAstroNOT** [comment]
Ya leave it, it's too funny
