### ISSUE TITLE
New Femc bust up portrait

### ISSUE THREAD

**Issue by Lisa9388** [MadMax1960/Femc-Reloaded-Project#180]
![FEMC R Portrait 1](https://github.com/user-attachments/assets/eecae98b-6785-4210-a884-01b096e41f86)
Hello everyone,

ever since I learned from your femc project, I wanted to contribute something to it as well. I know that you already have a lot of bust up portraits but if possible consider taking mine as well. I tried to make it as close as possible to the original Portable version. I'm not sure about the size however and the shadowing part up from the neck so please inform me if it can be used the way it is. I will create the blinking animation as soon as I know that it's usable.

**Comment by raycopper** [comment]
Of course we would love to include your bustup too
If you have discord please join our server https://discord.gg/yxtDmX7qXd
Then we can go through what's needed so we can put it ingame ^^
