### ISSUE TITLE
JP audio switches to EN audio for cutscenes after 1.1.0 update

### ISSUE THREAD

**Issue by phantom-m** [MadMax1960/Femc-Reloaded-Project#184]
While playing 1.2.1, the cutscene when the player first awakens their persona, the audio swaps back to English temporarily even though it's set to Japanese in the settings. 

After the cutscene ends, it returns back to Japanese audio. I haven't played far enough to know whether this happens for later cutscenes yet.

After testing out the previous releases listed on the releases page, it looks like this starts happening after the 1.1.0 release. It didn't happen when I tested 1.0.8.

**Comment by MadMax1960** [comment]
Uhhh this might be a ryo issue? I'll add a proper toggle for english audio in a future update to just fix this no matter what though. Thanks for reporting.
