### ISSUE TITLE
Missing(?) party icon

### ISSUE THREAD

**Issue by Dark-Blue-Moon** [MadMax1960/Femc-Reloaded-Project#187]
Don't know if she just doesn't have a colored icon or I fucked something up but when in the menu she has the correct icon but in Tartarus her icon is still Makoto's.
![image_2024-08-15_153425976](https://github.com/user-attachments/assets/72b53733-38dc-448a-85da-3007db143a79)
![image](https://github.com/user-attachments/assets/5737ac02-3a2f-4116-a18b-7059f9801e19)

**Comment by MadMax1960** [comment]
Reboot might fix

**Comment by Dark-Blue-Moon** [comment]
> Reboot might fix

Tried that, hasnt worked the past 3 times

**Comment by TheBestAstroNOT** [comment]
Attempt reinstalling the femc mod and all it's dependencies. Delete all mods in urs mod folder and then reinstall.
