### ISSUE TITLE
School uniform doesnt change during days off

### ISSUE THREAD

**Issue by Miguia4444** [MadMax1960/Femc-Reloaded-Project#188]
![imagen_2024-08-16_213249472](https://github.com/user-attachments/assets/1af85f59-05b7-4a26-8e4c-aafa1e182160)
The clothes change normally when working part time or in the night visits from the kid, but on sundays or any other days without schools, it keeps the uniform, is this a known issue? or did i mess up installing the mod or something like that?

**Comment by MadMax1960** [comment]
Winter casual isn't done yet, so I redirect to normal winter uniform in the meantime
