### ISSUE TITLE
The Music is not replaced and the Cut in too.

### ISSUE THREAD

**Issue by rdev3** [MadMax1960/Femc-Reloaded-Project#191]
The music is still using the original, this does not happen in 1.2.1 version. But the battle music is working fine in 1.3.0.

Also. the cut ins are not replaced. this also does not happen in 1.2.1 version. But its appearing when the glass/cut in break (weird).

https://github.com/user-attachments/assets/f74f88a7-9e02-47aa-a88a-4f721f8c7609

https://github.com/user-attachments/assets/546da6b0-debf-447b-9ea1-997240705470

**Comment by TheBestAstroNOT** [comment]
Delete the folder of the mod and reinstall

**Comment by rdev3** [comment]
> Delete the folder of the mod and reinstall

already tried it, still no luck.

**Comment by TheBestAstroNOT** [comment]
Check if ryo is installed

**Comment by rdev3** [comment]
> Check if ryo is installed

it's already installed. still no luck :(

**Comment by TheBestAstroNOT** [comment]
reinstall everything then, nuke ur reloaded folder and start from scratch

**Comment by rdev3** [comment]
> reinstall everything then, nuke ur reloaded folder and start from scratch

actually, i already tried it before. tried to reinstall the mods even reinstalling the reloaded. still the same.

**Comment by TheBestAstroNOT** [comment]
Can you send me a pic of ur mod order

**Comment by rdev3** [comment]
here.

![image](https://github.com/user-attachments/assets/2b3e44f7-53c6-46cf-b7aa-c8513f4f7345)

**Comment by TheBestAstroNOT** [comment]
Enable all of these 
![image](https://github.com/user-attachments/assets/499c71cc-3136-4b04-a429-6230eb82a06a)
Also move femc project to the very top

**Comment by rdev3** [comment]
> Enable all of these ![image](https://private-user-images.githubusercontent.com/139786546/363240436-499c71cc-3136-4b04-a429-6230eb82a06a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTU1ODYsIm5iZiI6MTcyNTA5NTI4NiwicGF0aCI6Ii8xMzk3ODY1NDYvMzYzMjQwNDM2LTQ5OWM3MWNjLTMxMzYtNGIwNC1hNDI5LTYyMzBlYjgyYTA2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwOTA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTdkNmU1NThjNGJiNTg3NTAwYjkxNjdmMTJkOGRiMmYzNjRiODg2YmY5OGFhNzRjMWU5YTRhOWU2YTBjZjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q9TRSpnkyyqLE_VdiCAlLLgRthIzdlpQQT5Cl2spjCs) Also move femc project to the very top

so, the cut ins finally fixed (yay) 
https://github.com/user-attachments/assets/cf3e9837-c673-4746-8685-cdd271f94abe

unfortunately, the outside music is still not fixed :(

**Comment by TheBestAstroNOT** [comment]
> > Enable all of these ![image](https://private-user-images.githubusercontent.com/139786546/363240436-499c71cc-3136-4b04-a429-6230eb82a06a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTU1ODYsIm5iZiI6MTcyNTA5NTI4NiwicGF0aCI6Ii8xMzk3ODY1NDYvMzYzMjQwNDM2LTQ5OWM3MWNjLTMxMzYtNGIwNC1hNDI5LTYyMzBlYjgyYTA2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwOTA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTdkNmU1NThjNGJiNTg3NTAwYjkxNjdmMTJkOGRiMmYzNjRiODg2YmY5OGFhNzRjMWU5YTRhOWU2YTBjZjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q9TRSpnkyyqLE_VdiCAlLLgRthIzdlpQQT5Cl2spjCs) Also move femc project to the very top
> 
> so, the cut ins finally fixed (yay) ![image](https://private-user-images.githubusercontent.com/151295594/363402843-09079f42-cde7-47a5-887e-3715f766195c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTc5MDAsIm5iZiI6MTcyNTA5NzYwMCwicGF0aCI6Ii8xNTEyOTU1OTQvMzYzNDAyODQzLTA5MDc5ZjQyLWNkZTctNDdhNS04ODdlLTM3MTVmNzY2MTk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwOTQ2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmMxOTA2MjFlZjExMTk0OTMzZDJkMDIwNTA1YzgxNTNjZGZmN2E2ZDlkYTNmZGY2MDdhYTJmNmI2YzgyMGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zM6eJkaPqE5yNAuDiBPAiJihlymrVo1-biR8tnGwxMI)
> 
> unfortunately, the outside music is still not fixed :(

have you enabled the music in the config

**Comment by rdev3** [comment]
> > > Enable all of these ![image](https://private-user-images.githubusercontent.com/139786546/363240436-499c71cc-3136-4b04-a429-6230eb82a06a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTU1ODYsIm5iZiI6MTcyNTA5NTI4NiwicGF0aCI6Ii8xMzk3ODY1NDYvMzYzMjQwNDM2LTQ5OWM3MWNjLTMxMzYtNGIwNC1hNDI5LTYyMzBlYjgyYTA2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwOTA4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTdkNmU1NThjNGJiNTg3NTAwYjkxNjdmMTJkOGRiMmYzNjRiODg2YmY5OGFhNzRjMWU5YTRhOWU2YTBjZjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q9TRSpnkyyqLE_VdiCAlLLgRthIzdlpQQT5Cl2spjCs) Also move femc project to the very top
> > 
> > 
> > so, the cut ins finally fixed (yay) ![image](https://private-user-images.githubusercontent.com/151295594/363402843-09079f42-cde7-47a5-887e-3715f766195c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTc5MDAsIm5iZiI6MTcyNTA5NzYwMCwicGF0aCI6Ii8xNTEyOTU1OTQvMzYzNDAyODQzLTA5MDc5ZjQyLWNkZTctNDdhNS04ODdlLTM3MTVmNzY2MTk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQwOTQ2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmMxOTA2MjFlZjExMTk0OTMzZDJkMDIwNTA1YzgxNTNjZGZmN2E2ZDlkYTNmZGY2MDdhYTJmNmI2YzgyMGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zM6eJkaPqE5yNAuDiBPAiJihlymrVo1-biR8tnGwxMI)
> > unfortunately, the outside music is still not fixed :(
> 
> have you enabled the music in the config

yes. i still use default settings (it automatically enabled the music)
