### ISSUE TITLE
The gendered audio, stopped working 

### ISSUE THREAD

**Issue by Miguia4444** [MadMax1960/Femc-Reloaded-Project#195]
At first i thought that maybe simple it wasnt full yet and the whole game didnt have the gendered audio, but i made a new run just to check on a scene i knew for sure it had the gendered audio, but it also didnt work, i tried deactivating it and activating it again, reinstalling the mod, but nothing worked, i dont know if this is a problem with the new patch or something else since i am not sure when this started.

**Comment by TheBestAstroNOT** [comment]
This is a know issue and will be fixed in the next patch. It was broken accidentially when making the new music system.

**Comment by Miguia4444** [comment]
I see, its a relief to know, thanks for the reply
