### ISSUE TITLE
Femc mod crashing when I enter stores or talk to people

### ISSUE THREAD

**Issue by Laccooo** [MadMax1960/Femc-Reloaded-Project#218]
any time I enter certain buildings or talk to people the game crashes and the crash report tells me,

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000008

0x00007ffa3688fabc KERNELBASE.dll!UnknownFunction []
0x00007ff9da01c952 coreclr.dll!UnknownFunction []
0x00007ff9d9e70f44 coreclr.dll!UnknownFunction []
0x00007ffa39107f9a ntdll.dll!UnknownFunction []
0x00007ffa390ae642 ntdll.dll!UnknownFunction []
0x00007ffa391341ce ntdll.dll!UnknownFunction []
0x00007ff97c0d8fd9 UnknownFunction []
0x000000015ce432f8 UnknownFunction []
0x00000000c1300000 UnknownFunction []
0x000000003f800000 UnknownFunction []

Anyone know if I can do anything to fix this?

**Comment by MadMax1960** [comment]
The updated build in the discord being tested fixes this

**Comment by Laccooo** [comment]
I assume this build will be released soon then?
