### ISSUE TITLE
FEMC Mod crashes upon voice lines (LINUX/STEAM DECK)

### ISSUE THREAD

**Issue by souljolt** [MadMax1960/Femc-Reloaded-Project#220]
Hi, I'm new to P3R modding and wanted to play this mod, so I went through the hassle of setting up mods for this game. After I had finished that process I downloaded this, and put it in Reloaded-II  and I got an error (as shown in the picture)  and after downloading the said mod, it still appeared even after I made sure it was enabled.  The game still opens, but the mod doesn't work.
![Screenshot_20241011_185835](https://github.com/user-attachments/assets/233d2bbe-0371-48d2-aded-2eec015dced1)

**Comment by MadMax1960** [comment]
I would manually reinstall femc mod or just that mod and try again. Could be a r2 steam deck issue too? But probably the former not the latter.

**Comment by souljolt** [comment]
> I would manually reinstall femc mod or just that mod and try again. Could be a r2 steam deck issue too? But probably the former not the latter.

Did exactly that, and the game started without any errors, but before the game even got to the title screen, a unreal engine error appeared.
I tried again, but then crashed again once Kotone walked into the dorm, right before Pharos introduces himself.  I presume that the more I boot it up it'll be able to load more and more.

**Comment by souljolt** [comment]
After going in gaming mode, the same happens. Once Pharos is about to talk, the game crashes. Even if I boot up a different save file, the game crashes when somebody talks, specifically if there's a voice line, whether it be a small noise or a fully voiced line.

**Comment by souljolt** [comment]
Even if the voice line volume is turned off, the game still crashes.

**Comment by MadMax1960** [comment]
Oh oops, in the discord there's a updated version for ep Aigis, you should probably rock that ver for now

**Comment by souljolt** [comment]
> Oh oops, in the discord there's a updated version for ep Aigis, you should probably rock that ver for now

Can you send a link to the message? I can't find it anywhere lol

**Comment by souljolt** [comment]
NVM I found it

**Comment by souljolt** [comment]
With the update, it works great! Thank you so much for the help! Femc forever 🤞🤞
