### ISSUE TITLE
JP audio switches to EN audio for cutscenes in v1.5.1

### ISSUE THREAD

**Issue by weskeryiu** [MadMax1960/Femc-Reloaded-Project#229]
Hello, I have the same issue as this [post](https://github.com/MadMax1960/Femc-Reloaded-Project/issues/184). This [cutscene](https://www.youtube.com/watch?v=EgXPbIMKyyk) audio switches to English even though I set my game to Japanese. I've turned off "Gendered Audio" and set the "Voice Options" to Japanese, but the issue still happens in v1.5.1. What option should I turn off to switch it back to Japanese? Or which file is related to the cutscene audio? Maybe I could just delete them so the game plays the original audio instead of the Femc mod one?

**Comment by MadMax1960** [comment]
Oh uh this should actually be the only cutscene that does this, we added WIP support for this scene using some lines Melodi recorded. We don't have the Japanese version of this scene voiced though, so if you just play past it, it should work fine.

**Comment by weskeryiu** [comment]
I guess I'll watch this cutscene in Japanese on YouTube then. Thanks for the quick reply.
