### ISSUE TITLE
Skirt issue in Tartarus/Velvet

### ISSUE THREAD

**Issue by TemptedGhost** [MadMax1960/Femc-Reloaded-Project#39]
SKIRT TARTARUS BUG:

When in the Tartarus: Entrance. it'll look normal when moving around or just idle, but as soon you enter the floor or velvet room.
it'll be stretched out and the skirt animations won't work

https://github.com/MadMax1960/Femc-Reloaded-Project/assets/160564665/a5a41b70-daf9-4326-a628-a052381dd38c

**Comment by TemptedGhost** [comment]
I don't know if this is intentional! if it is then sorry for making this report

**Comment by MadMax1960** [comment]
Custom anims aren't possible yet and the clipping isn't egregious, wouldn't call this an issue here specifically.
