### ISSUE TITLE
Menu minor issue

### ISSUE THREAD

**Issue by TemptedGhost** [MadMax1960/Femc-Reloaded-Project#40]
When you open up the " Skill/Item" Section
Kotone's face will have a glitch/error on her lips

![image](https://github.com/MadMax1960/Femc-Reloaded-Project/assets/160564665/e135f246-360a-4ec2-9c1f-527d2306efea)
![image](https://github.com/MadMax1960/Femc-Reloaded-Project/assets/160564665/efa22dfb-ddea-4a6e-905b-aaace8c7d3c2)

**Comment by MadMax1960** [comment]
Issue is the outline mesh on the face model.

**Comment by fernhw** [comment]
added to trello https://trello.com/c/2v8aGBS6/307-bug-fix-outline-mesh-in-menu-3dui
