### ISSUE TITLE
She'll stand up too all but spiritually she'll sit

### ISSUE THREAD

**Issue by TemptedGhost** [MadMax1960/Femc-Reloaded-Project#41]
![image](https://github.com/MadMax1960/Femc-Reloaded-Project/assets/160564665/3253afb7-885e-4a69-96aa-a4e7ae00dcbb)

**Comment by MadMax1960** [comment]
Not high on priority list, but it is funny. Can't fix due to no custom anims or bps of that sort yet.

**Comment by fernhw** [comment]
trello https://trello.com/c/zewIEJ1x/310-bug-shell-stand-up-but-will-sit-in-spirit link
