### ISSUE TITLE
Render distance bug? ( IDK )

### ISSUE THREAD

**Issue by TemptedGhost** [MadMax1960/Femc-Reloaded-Project#42]
If you are too far away from the camera, the model will begin to crumble apart

https://github.com/MadMax1960/Femc-Reloaded-Project/assets/160564665/ce90ee90-b236-422f-918c-902351dfbbf9

**Comment by MadMax1960** [comment]
This seems to happen with every custom import including when I do lod models. 

Not a fix but leaving explanation here for future me.

**Comment by fernhw** [comment]
Acknowledged: sent to trello backlog 
link https://trello.com/c/MJ4gsJJ1/311-bug-lod-breaks-on-model
