### ISSUE TITLE
Disparity between 1.0.3 and files present on github. 

### ISSUE THREAD

**Issue by MadMax1960** [MadMax1960/Femc-Reloaded-Project#44]
![image](https://github.com/MadMax1960/Femc-Reloaded-Project/assets/30520119/3ef066db-a369-4827-96bb-49876e2a45c5)

files should be overwritten for 1.0.4

**Comment by fernhw** [comment]
sent to backlog: https://trello.com/c/jIhtoQES/312-bug-disparity-between-103-and-files-present-on-github-44
